# Datasource (overridden by env in Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/notesdb
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true